---
- hosts: all
  become: true
  remote_user: ubuntu
  gather_facts: no
  pre_tasks:
  - name: install python
    raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python python-pip)"
    register: output
    changed_when: output.stdout != ""

- hosts: all
  become: true
  remote_user: ubuntu
  gather_facts: yes
  tasks:
    - name: Add hostname to /etc/hosts
      lineinfile:
        path: /etc/hosts
        state: present
        line: "127.0.0.1 {{ansible_hostname}}"
    - name: Install aptitude
      apt:
        name: aptitude
        state: present
    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        state: latest
# Copied out of https://github.com/savoirfairelinux/ansible-reboot-if-needed/blob/master/tasks/main.yml
    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
    - name: Rebooting machine
      shell: sleep 2 && shutdown -r now "Ansible updates triggered"
      async: 1
      poll: 0
      ignore_errors: true
      when: reboot_required_file.stat.exists
    - name: Waiting for the machine to come back
      local_action: wait_for host={{ ansible_host }} state=started port=22 delay=30
      become: no
      when: reboot_required_file.stat.exists

- hosts: apphosts
  become: true
  remote_user: ubuntu
  tasks:
    - name: installing repo for Java 8 in Ubuntu
      apt_repository: repo='ppa:openjdk-r/ppa'
  roles:
    - role: geerlingguy.java
      when: "ansible_os_family == 'Debian'"
      java_packages:
        - openjdk-8-jdk

- hosts: webhosts
  become: true
  remote_user: ubuntu
  vars_files:
    - vars/main.yml
  roles:
    - geerlingguy.nginx
  tasks:
    - name: get static site from s3
      get_url:
        dest: "/tmp/site.tgz"
        url: "https://s3.us-east-2.amazonaws.com/inferences-static-site/inference_site.tgz"
        mode: 0744
    - name: create directory for static site
      file:
        path: "/var/www/inference.es"
        state: directory
        owner: "{{ nginx_user }}"
        mode: 02755
    - name: unpack site to nginx default site
      unarchive:
        dest: "/var/www/inference.es"
        remote_src: yes
        src: "/tmp/site.tgz"
        owner: "{{ nginx_user }}"
        mode: 0755
