---
- hosts: all
  become: true
  remote_user: ubuntu
  gather_facts: no
  pre_tasks:
  - name: install python
    raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python python-pip)"
    register: output
    changed_when: output.stdout != ""

- hosts: webhosts
  become: true
  remote_user: ubuntu
  vars_files:
    - vars/main.yml
  roles:
    - geerlingguy.nginx
  tasks:
    - name: get static site from s3
      get_url:
        dest: "/tmp/site.tgz"
        url: "https://s3.us-east-2.amazonaws.com/inferences-static-site/inference_site.tgz"
        mode: 0744
    - name: create directory for static site
      file:
        path: "/var/www/inference.es"
        state: directory
        owner: "{{ nginx_user }}"
        mode: 02744
    - name: unpack site to nginx default site
      unarchive:
        dest: "/var/www/inference.es"
        remote_src: yes
        src: "/tmp/site.tgz"
        owner: "{{ nginx_user }}"
        mode: 0744
